### ISSUE TITLE
No watch-only hd wallets found.

### ISSUE THREAD

**Issue by Geremia** [bwt-dev/bwt-electrum-plugin#3]
When clicking the "Connect to bitcoind" button, I get:

>No watch-only hd wallets found. Note that bwt cannot currently be used with hot wallets. See the README for more details.

I ran ```createwallet "watch_only" true true``` in Bitcoin Core terminal.

**Comment by shesek** [comment]
This is about not finding suitable Electrum wallets, not about bitcoind wallets.

Is this an offline/hardware wallet setup? As the message says, the Electrum plugin is (intentionally) incompatible with hot wallets.

If it's not a hot wallet, what kind of wallet is it? Regular HD, multi-signature, something else?

**Comment by Geremia** [comment]
>This is about not finding suitable Electrum wallets

How do I create a watch-only wallet in Electrum, then?

**Comment by shesek** [comment]
You have some instructions available here: https://electrum.readthedocs.io/en/latest/coldstorage.html

A watch-only wallet is also the standard setup for using hardware wallets with Electrum.

I'm hoping to enable hot wallet support in the bwt electrum plugin soon. But for now, if you are using a hot wallet, you can use bwt if you [set it up as a standalone server](https://github.com/bwt-dev/bwt#setting-up-bwt) instead of using the plugin.
